### ISSUE TITLE
Website not opening

### ISSUE THREAD

**Issue by AviralCoder** [devSahinur/amazon-clone#1]
Apperently, the website isn't opening for me.
![Screenshot 2021-08-28 at 10 23 13 PM](https://user-images.githubusercontent.com/82994899/131225109-1f1a5e1c-7ec4-448d-a609-02d5fcb19bbe.png)

Takes a lot of time to load and then vercel shows this

**Comment by devSahinur** [comment]
Okay I fixed it now check it out
https://amazon-clone-sahinur.vercel.app/

**Comment by AviralCoder** [comment]
yeah ok
